name: PlayerProfiles
version: '${project.version}'
main: me.wappen.playerprofiles.PlayerProfiles
api-version: 1.19
author: Wappen

commands:
  playerprofiles:
    permission: player-profiles.admin
  profile:
    permission: player-profiles.profile-cmd
permissions:
  player-profiles.*:
    children:
      player-profiles.profile-cmd: true
      player-profiles.admin: true
  player-profiles.profile-cmd:
    default: true
  player-profiles.admin:
    default: false
